export const STAKE5DAYS_CONTRACT = "0xb0B62e987dA7a3CfBB7b0e92EcebcFF446b315d2";

export const STAKE5DAYS_ABI = [
  {
    inputs: [
      { internalType: "contract IERC20", name: "_token", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "stakeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "daysClaimed",
        type: "uint16",
      },
    ],
    name: "InterestClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "stakeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "capital",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalInterest",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startAt",
        type: "uint256",
      },
    ],
    name: "StakeAssigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "stakeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "capitalWithdrawn",
    type: "event",
  },
  {
    inputs: [],
    name: "DAY",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "INTEREST_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LOCK_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TOTAL_DAYS",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "capital", type: "uint256" },
      { internalType: "uint256", name: "totalInterest", type: "uint256" },
    ],
    name: "assignStake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "claimInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "getClaimableInterest",
    outputs: [
      { internalType: "uint256", name: "claimableAmount", type: "uint256" },
      { internalType: "uint16", name: "claimableDays", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "getEndDate",
    outputs: [{ internalType: "uint256", name: "endDate", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "getStake",
    outputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "capital", type: "uint256" },
      { internalType: "uint256", name: "totalInterest", type: "uint256" },
      { internalType: "uint256", name: "startAt", type: "uint256" },
      { internalType: "uint256", name: "capitalWithdrawnAt", type: "uint256" },
      { internalType: "uint16", name: "daysClaimed", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "getStakeIdsByAccount",
    outputs: [
      { internalType: "uint256[]", name: "stakeIds", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "getStakeInfo",
    outputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "capital", type: "uint256" },
      { internalType: "uint256", name: "totalInterest", type: "uint256" },
      { internalType: "uint256", name: "startDate", type: "uint256" },
      { internalType: "uint256", name: "endDate", type: "uint256" },
      { internalType: "uint256", name: "capitalWithdrawnAt", type: "uint256" },
      { internalType: "uint16", name: "daysClaimed", type: "uint16" },
      { internalType: "uint256", name: "daysRemaining", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "contract IERC20", name: "rescueToken", type: "address" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "rescueERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "stakes",
    outputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "capital", type: "uint256" },
      { internalType: "uint256", name: "totalInterest", type: "uint256" },
      { internalType: "uint256", name: "startAt", type: "uint256" },
      { internalType: "uint256", name: "capitalWithdrawnAt", type: "uint256" },
      { internalType: "uint16", name: "daysClaimed", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "stakeId", type: "uint256" }],
    name: "withdrawCapital",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
